---
- name: Install Apache Web Server
  hosts: localhost
  become: yes
  tasks:
  # - name: Fix dpkg status file if corrupted
   #   become: yes
    #  shell: |
     #    cp /var/lib/dpkg/status-old /var/lib/dpkg/status || true
      #   apt-get update

 #   - name: Install Apache
  #    apt:
   #     name: apache2
    #    state: present

   # - name: Start Apache service
    #  service:
     #   name: apache2
     #   state: started
    #    enabled: yes
        
   # - name: Download wordpress
     # get_url:
     #    url: https://wordpress.org/latest.tar.gz
    #     dest: /tmp/wordpress.tar.gz
         
   # - name: Extract
      #unarchive:
        # src: /tmp/wordpress.tar.gz
        # dest: /var/www/html/
       #  remote_src: yes 

    - name: Copy files
      become: yes
      shell: |
         cp /var/www/html/wordpress /var/www/html
