---
- name: Install Apache Web Server
  hosts: localhost
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Remove index.html file
      file:
        path: /var/www/html/index.html
        state: absent
